import i18n from 'i18next'
import LanguageDetector from 'i18next-browser-languagedetector'
import { initReactI18next } from 'react-i18next'

const resources = {
  he: {
    translation: {
      home: 'בית',
      products: 'מוצרים',
      profile: 'פרופיל',
      about: 'אודות',
      barBook: 'ספר בר',
      orders: 'הזמנות',
      itemsManagement: 'ניהול מוצרים',
      cart: 'עגלת קניות',
      // Home page
      dailyTask: 'משימה יומית',
      day_0: 'ראשון',
      day_1: 'שני',
      day_2: 'שלישי',
      day_3: 'רביעי',
      day_4: 'חמישי',
      day_5: 'שישי',
      day_6: 'שבת',
      dayPrefix: 'יום',
      dailyTaskFallback: 'בדוק מלאי ועדכן את ספר הבר',
      statTotalProducts: 'סה"כ מוצרים',
      statAvailableProducts: 'מוצרים זמינים',
      statLowStock: 'מלאי נמוך',
      statTotalOrders: 'סה"כ הזמנות',
      statPendingOrders: 'הזמנות ממתינות',
      statTodayRevenue: 'הכנסות היום',
      lowStockAlerts: 'התראות מלאי נמוך',
      stockLabel: 'מלאי',
      alertThresholdLabel: 'רף התראה',
      viewAllLowStock: 'צפה בכל המוצרים עם מלאי נמוך',
      recentOrders: 'הזמנות אחרונות',
      viewAll: 'צפה בהכל',
      orderId: 'הזמנה',
      itemsCount: 'פריטים',
      status_pending: 'ממתין',
      status_completed: 'הושלם',
      status_delivered: 'נמסר',
      // Header
      hello: 'שלום',
      logout: 'התנתק',
      loginRequired: 'יש להתחבר תחילה',
      toggleLanguage: 'החלף שפה',
      openSidebar: 'פתח תפריט',
      closeSidebar: 'סגור תפריט',
      // Bar Book
      barBookTitle: 'ספר בר',
      tabChecklists: 'צ\'קליסטים',
      tabPages: 'דפי מלאים',
      tabDaily: 'משימות יומיות',
      tabRecipes: 'מתכונים',
      loadingBarBook: 'טוען ספר בר...',
      errorLoadBarBook: 'שגיאה בטעינת ספר הבר',
      dailyTasksTitle: 'משימות יומיות',
      dailyTasksIntro: 'משימות יומיות מתבצעות בכל משמרת. המשימה מתבצעת לפי יום בשבוע.',
      dayColumn: 'יום',
      dailyTaskColumn: 'משימה יומית',
      clickToEdit: 'לחץ לעריכה',
      deleteRow: 'מחק שורה',
      deleteItem: 'מחק משימה',
      deleteDay: 'מחק יום',
      addTask: 'הוסף משימה',
      addDay: 'הוסף יום',
      clearContent: 'נקה תוכן',
      newDay: 'יום חדש',
      dailyTaskPlaceholder: 'כתוב כאן את כל המשימות ליום זה...',
      emptyCell: '(ריק)',
      emptyClickEdit: '(ריק – לחץ לעריכה)',
      confirmClearBarBook: 'לנקות את כל תוכן ספר הבר? כל התוכן יימחק.',
      // Recipes
      recipesTitle: 'מתכונים',
      addRecipe: 'הוסף מתכון',
      loadingRecipes: 'טוען מתכונים...',
      noRecipes: 'אין מתכונים. הוסף מתכון ראשון.',
      editRecipe: 'ערוך מתכון',
      deleteRecipe: 'מחק מתכון',
      edit: 'ערוך',
      delete: 'מחק',
      ingredients: 'מרכיבים',
      instructions: 'אופן ההכנה',
      editingRecipe: 'עריכת מתכון',
      addingRecipe: 'הוספת מתכון',
      recipeNameLabel: 'שם המתכון',
      recipeNamePlaceholder: 'למשל: סירופ קינמון',
      ingredientsLabel: 'מרכיבים (שורה אחת לכל מרכיב)',
      instructionsLabel: 'אופן ההכנה (שורה אחת לכל שלב)',
      saveChanges: 'שמור שינויים',
      cancel: 'ביטול',
      recipeTitleRequired: 'שם המתכון חובה',
      minOneIngredient: 'יש להזין לפחות מרכיב אחד',
      minOneStep: 'יש להזין לפחות שלב אחד',
      confirmDeleteRecipe: 'למחוק את המתכון',
      ingredientsPlaceholder: 'מי סוכר\nכוסברה\nמחית פסיפלורה',
      instructionsPlaceholder: 'נערבל את המרכיבים.\nנסנן ונסיים.',
      // Orders list
      ordersListTitle: 'רשימת הזמנות',
      noOrders: 'אין הזמנות',
      dateColumn: 'תאריך',
      downloadPdf: 'הורד PDF',
      deleteOrder: 'מחק הזמנה',
      itemColumn: 'פריט',
      quantityColumn: 'כמות',
      itemRemoved: 'הוסר',
      undo: 'החזר',
      removeItemFromOrder: 'הסר פריט מההזמנה',
      noItems: 'אין פריטים',
      confirmDeleteOrder: 'האם אתה בטוח שברצונך למחוק את ההזמנה?',
      orderDeletedSuccess: 'ההזמנה נמחקה בהצלחה',
      orderDeleteError: 'שגיאה במחיקת ההזמנה',
      orderUpdatedSuccess: 'ההזמנה עודכנה בהצלחה',
      orderUpdateError: 'שגיאה בעדכון ההזמנה',
      pdfError: 'שגיאה ביצירת הקובץ',
      noSupplier: 'ללא ספק',
      itemNumber: 'פריט {{n}}',
      // Items management
      itemsManagementTitle: 'ניהול מוצרים',
      noProductsInSystem: 'אין מוצרים במערכת',
      category: 'קטגוריה',
      allCategories: 'כל הקטגוריות',
      supplier: 'ספק',
      allSuppliers: 'כל הספקים',
      stock: 'מלאי',
      all: 'הכל',
      inStock: 'במלאי',
      outOfStock: 'לא במלאי',
      lowStockFilter: 'מלאי נמוך',
      showingProducts: 'מציג {{count}} מתוך {{total}} מוצרים',
      clearFilters: 'נקה פילטרים',
      createOrder: 'צור הזמנה ({{n}})',
      importStockExcel: 'ייבוא מלאי מאקסל',
      uploadDocument: 'העלאת מסמך',
      addProduct: 'הוסף מוצר',
      selectOrdersToCreate: 'בחר אילו הזמנות ליצור',
      createOrderModalDesc: 'נבחרו מוצרים להזמנה לפי ספק. סמן את הספקים שאליהם תרצה לשלוח הזמנה.',
      productsCount: '{{n}} מוצרים',
      combinedOrderOption: 'יצירת הזמנה משולבת – איחוד כל המוצרים הנבחרים להזמנה אחת',
      createSelectedOrders: 'צור הזמנות נבחרות',
      importStockTitle: 'ייבוא מלאי מאקסל',
      fileLabel: 'קובץ',
      loading: 'טוען...',
      totalRows: 'סה״כ שורות',
      matchedRows: 'שורות שנמצאה התאמה',
      uniqueItemsToUpdate: 'פריטים ייחודיים שיעודכנו',
      unmatchedRows: 'שורות ללא התאמה',
      showUnmatched: 'הצג שורות ללא התאמה',
      andMore: '... ועוד {{n}}',
      applyStockUpdate: 'החל עדכון מלאי',
      close: 'סגור',
      editProduct: 'ערוך מוצר',
      addNewProduct: 'הוסף מוצר חדש',
      nameHe: 'שם (עברית)',
      nameEn: 'שם (אנגלית)',
      description: 'תיאור',
      selectCategory: 'בחר קטגוריה',
      noCategoriesAvailable: 'אין קטגוריות זמינות',
      categoriesFromProducts: 'נמצאו {{n}} קטגוריות מהמוצרים הקיימים',
      noCategoriesInProducts: 'לא נמצאו קטגוריות במוצרים הקיימים',
      price: 'מחיר',
      stockQuantity: 'כמות במלאי',
      optimalStock: 'כמות אופטימלית למלאי',
      imageUrl: 'תמונה (URL)',
      availableForOrder: 'זמין להזמנה',
      update: 'עדכן',
      save: 'שמור',
      nameColumn: 'שם',
      orderQuantity: 'כמה להזמין',
      actions: 'פעולות',
      noProductsMatchFilters: 'לא נמצאו מוצרים התואמים לפילטרים שנבחרו',
      remove: 'הסר',
      confirmDeleteItem: 'האם אתה בטוח שברצונך למחוק את הפריט?',
      itemDeletedSuccess: 'הפריט נמחק בהצלחה',
      itemDeleteError: 'שגיאה במחיקת הפריט',
      itemSavedSuccess: 'הפריט נוסף בהצלחה',
      itemUpdatedSuccess: 'הפריט עודכן בהצלחה',
      itemSaveError: 'שגיאה בשמירת הפריט',
      optimalUpdated: 'כמות אופטימלית עודכנה',
      optimalUpdateError: 'שגיאה בעדכון הכמות האופטימלית',
      noProductsToOrder: 'אין מוצרים להזמנה',
      selectAtLeastOneSupplier: 'נא לבחור לפחות ספק אחד',
      combinedOrderLabel: 'הזמנה משולבת',
      orderCreatedProducts: 'הזמנה נוצרה – {{n}} מוצרים',
      ordersCreatedProducts: 'נוצרו {{c}} הזמנות – {{n}} מוצרים',
      createOrdersError: 'שגיאה ביצירת ההזמנות',
      stockUpdatedSuccess: 'המלאי עודכן בהצלחה',
      stockUpdateError: 'שגיאה בעדכון המלאי',
      readFileError: 'שגיאה בקריאת הקובץ',
      noCategory: 'ללא קטגוריה',
      noValidRows: 'לא נמצאו שורות תקינות. בדוק שיש עמודות שם + מלאי (כמות).',
      // Order page (cart)
      cartTitle: 'עגלת קניות',
      cartEmpty: 'העגלה ריקה',
      supplierLabel: 'ספק',
      quantityLabel: 'כמות',
      totalLabel: 'סה"כ',
      checkoutNow: 'הזמן עכשיו (לפי ספק)',
      clearCart: 'נקה עגלה',
      // Products / menu page
      cannotLoadProducts: 'לא ניתן לטעון מוצרים',
      cannotLoadItemDetails: 'לא ניתן לטעון פרטי מוצר',
      itemNotFound: 'המוצר לא נמצא',
      searchSectionTitle: 'חיפוש',
      categoriesFilterTitle: 'קטגוריות',
      searchProductsPlaceholder: 'חפש מוצרים...',
      clearSearch: 'נקה חיפוש',
      addToCart: 'הוסף לעגלה',
      available: 'זמין',
      unavailable: 'לא זמין',
      allCategoriesFilter: 'הכל',
      paginationPrev: 'קודם',
      paginationNext: 'הבא',
      noItemsFound: 'לא נמצאו מוצרים',
      addToCartButton: 'הוסף לעגלה',
      // Category names (filter buttons – when data has English name)
      category_ALCOHOL: 'אלכוהול',
      category_WINE: 'יין',
      chartTitle: 'כמות הפריטים שהוזמנה מכל ספק בכל יום',
      chartItemsAxis: 'כמות פריטים',
      chartDateAxis: 'תאריך',
      chartItemsSuffix: 'פריטים',
      noOrderDataYet: 'אין עדיין נתוני הזמנות להצגה.',
    },
  },
  en: {
    translation: {
      home: 'Home',
      products: 'Products',
      profile: 'Profile',
      about: 'About',
      barBook: 'Bar Book',
      orders: 'Orders',
      itemsManagement: 'Items Management',
      cart: 'Cart',
      dailyTask: 'Daily Task',
      day_0: 'Sunday',
      day_1: 'Monday',
      day_2: 'Tuesday',
      day_3: 'Wednesday',
      day_4: 'Thursday',
      day_5: 'Friday',
      day_6: 'Saturday',
      dayPrefix: '',
      dailyTaskFallback: 'Check stock and update the bar book',
      statTotalProducts: 'Total Products',
      statAvailableProducts: 'Available Products',
      statLowStock: 'Low Stock',
      statTotalOrders: 'Total Orders',
      statPendingOrders: 'Pending Orders',
      statTodayRevenue: "Today's Revenue",
      lowStockAlerts: 'Low Stock Alerts',
      stockLabel: 'Stock',
      alertThresholdLabel: 'Alert threshold',
      viewAllLowStock: 'View all products with low stock',
      recentOrders: 'Recent Orders',
      viewAll: 'View all',
      orderId: 'Order',
      itemsCount: 'items',
      status_pending: 'pending',
      status_completed: 'completed',
      status_delivered: 'delivered',
      hello: 'Hello',
      logout: 'Logout',
      loginRequired: 'Please sign in first',
      toggleLanguage: 'Toggle language',
      openSidebar: 'Open menu',
      closeSidebar: 'Close menu',
      barBookTitle: 'Bar Book',
      tabChecklists: 'Checklists',
      tabPages: 'Stock pages',
      tabDaily: 'Daily tasks',
      tabRecipes: 'Recipes',
      loadingBarBook: 'Loading bar book...',
      errorLoadBarBook: 'Error loading bar book',
      dailyTasksTitle: 'Daily tasks',
      dailyTasksIntro: 'Daily tasks are performed every shift. The task is performed by day of the week.',
      dayColumn: 'Day',
      dailyTaskColumn: 'Daily task',
      clickToEdit: 'Click to edit',
      deleteRow: 'Delete row',
      deleteItem: 'Delete item',
      deleteDay: 'Delete day',
      addTask: 'Add task',
      addDay: 'Add day',
      clearContent: 'Clear content',
      newDay: 'New day',
      dailyTaskPlaceholder: 'Write all tasks for this day here...',
      emptyCell: '(empty)',
      emptyClickEdit: '(empty – click to edit)',
      confirmClearBarBook: 'Clear all bar book content? All content will be deleted.',
      recipesTitle: 'Recipes',
      addRecipe: 'Add recipe',
      loadingRecipes: 'Loading recipes...',
      noRecipes: 'No recipes. Add the first one.',
      editRecipe: 'Edit recipe',
      deleteRecipe: 'Delete recipe',
      edit: 'Edit',
      delete: 'Delete',
      ingredients: 'Ingredients',
      instructions: 'Instructions',
      editingRecipe: 'Edit recipe',
      addingRecipe: 'Add recipe',
      recipeNameLabel: 'Recipe name',
      recipeNamePlaceholder: 'e.g. Cinnamon syrup',
      ingredientsLabel: 'Ingredients (one per line)',
      instructionsLabel: 'Instructions (one step per line)',
      saveChanges: 'Save changes',
      cancel: 'Cancel',
      recipeTitleRequired: 'Recipe name is required',
      minOneIngredient: 'Enter at least one ingredient',
      minOneStep: 'Enter at least one step',
      confirmDeleteRecipe: 'Delete recipe',
      ingredientsPlaceholder: 'Sugar water\nCoriander\nPassion fruit puree',
      instructionsPlaceholder: 'Mix the ingredients.\nStrain and finish.',
      // Orders list
      ordersListTitle: 'Orders List',
      noOrders: 'No orders',
      dateColumn: 'Date',
      downloadPdf: 'Download PDF',
      deleteOrder: 'Delete order',
      itemColumn: 'Item',
      quantityColumn: 'Quantity',
      itemRemoved: 'removed',
      undo: 'Undo',
      removeItemFromOrder: 'Remove item from order',
      noItems: 'No items',
      confirmDeleteOrder: 'Are you sure you want to delete this order?',
      orderDeletedSuccess: 'Order deleted successfully',
      orderDeleteError: 'Error deleting order',
      orderUpdatedSuccess: 'Order updated successfully',
      orderUpdateError: 'Error updating order',
      pdfError: 'Error creating file',
      noSupplier: 'No supplier',
      itemNumber: 'Item {{n}}',
      // Items management
      itemsManagementTitle: 'Items Management',
      noProductsInSystem: 'No products in the system',
      category: 'Category',
      allCategories: 'All categories',
      supplier: 'Supplier',
      allSuppliers: 'All suppliers',
      stock: 'Stock',
      all: 'All',
      inStock: 'In stock',
      outOfStock: 'Out of stock',
      lowStockFilter: 'Low stock',
      showingProducts: 'Showing {{count}} of {{total}} products',
      clearFilters: 'Clear filters',
      createOrder: 'Create order ({{n}})',
      importStockExcel: 'Import stock from Excel',
      uploadDocument: 'Upload document',
      addProduct: 'Add product',
      selectOrdersToCreate: 'Select which orders to create',
      createOrderModalDesc: 'Products to order are grouped by supplier. Check the suppliers you want to send an order to.',
      productsCount: '{{n}} products',
      combinedOrderOption: 'Create combined order – merge all selected products into one order',
      createSelectedOrders: 'Create selected orders',
      importStockTitle: 'Import stock from Excel',
      fileLabel: 'File',
      loading: 'Loading...',
      totalRows: 'Total rows',
      matchedRows: 'Matched rows',
      uniqueItemsToUpdate: 'Unique items to update',
      unmatchedRows: 'Unmatched rows',
      showUnmatched: 'Show unmatched rows',
      andMore: '... and {{n}} more',
      applyStockUpdate: 'Apply stock update',
      close: 'Close',
      editProduct: 'Edit product',
      addNewProduct: 'Add new product',
      nameHe: 'Name (Hebrew)',
      nameEn: 'Name (English)',
      description: 'Description',
      selectCategory: 'Select category',
      noCategoriesAvailable: 'No categories available',
      categoriesFromProducts: 'Found {{n}} categories from existing products',
      noCategoriesInProducts: 'No categories found in existing products',
      price: 'Price',
      stockQuantity: 'Stock quantity',
      optimalStock: 'Optimal stock quantity',
      imageUrl: 'Image (URL)',
      availableForOrder: 'Available for order',
      update: 'Update',
      save: 'Save',
      nameColumn: 'Name',
      orderQuantity: 'Order qty',
      actions: 'Actions',
      noProductsMatchFilters: 'No products match the selected filters',
      remove: 'Remove',
      confirmDeleteItem: 'Are you sure you want to delete this item?',
      itemDeletedSuccess: 'Item deleted successfully',
      itemDeleteError: 'Error deleting item',
      itemSavedSuccess: 'Item added successfully',
      itemUpdatedSuccess: 'Item updated successfully',
      itemSaveError: 'Error saving item',
      optimalUpdated: 'Optimal quantity updated',
      optimalUpdateError: 'Error updating optimal quantity',
      noProductsToOrder: 'No products to order',
      selectAtLeastOneSupplier: 'Please select at least one supplier',
      combinedOrderLabel: 'Combined order',
      orderCreatedProducts: 'Order created – {{n}} products',
      ordersCreatedProducts: '{{c}} orders created – {{n}} products',
      createOrdersError: 'Error creating orders',
      stockUpdatedSuccess: 'Stock updated successfully',
      stockUpdateError: 'Error updating stock',
      readFileError: 'Error reading file',
      noCategory: 'No category',
      noValidRows: 'No valid rows found. Make sure there are name + stock (quantity) columns.',
      // Order page (cart)
      cartTitle: 'Shopping cart',
      cartEmpty: 'Cart is empty',
      supplierLabel: 'Supplier',
      quantityLabel: 'Quantity',
      totalLabel: 'Total',
      checkoutNow: 'Checkout now (by supplier)',
      clearCart: 'Clear cart',
      // Products / menu page
      cannotLoadProducts: 'Cannot load products',
      cannotLoadItemDetails: 'Cannot load item details',
      itemNotFound: 'Item not found',
      searchSectionTitle: 'Search',
      categoriesFilterTitle: 'Categories',
      searchProductsPlaceholder: 'Search products...',
      clearSearch: 'Clear search',
      addToCart: 'Add to cart',
      available: 'Available',
      unavailable: 'Unavailable',
      allCategoriesFilter: 'All',
      paginationPrev: 'Previous',
      paginationNext: 'Next',
      noItemsFound: 'No items found',
      addToCartButton: 'Add to Cart',
      chartTitle: 'Items ordered per supplier per day',
      chartItemsAxis: 'Item count',
      chartDateAxis: 'Date',
      chartItemsSuffix: 'items',
      noOrderDataYet: 'No order data to display yet.',
    },
  },
}

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'he',
    supportedLngs: ['he', 'en'],
    lng: 'he',
    debug: false,
    interpolation: {
      escapeValue: false,
    },
  })

function setDocumentLanguage(lng) {
  const lang = lng || i18n.language
  if (document.documentElement) {
    document.documentElement.lang = lang
    document.documentElement.setAttribute('dir', lang === 'he' ? 'rtl' : 'ltr')
  }
}
setDocumentLanguage()
i18n.on('languageChanged', setDocumentLanguage)

export default i18n
