// Demo data for local storage
export const demoCategories = [
  {
    _id: 'cat1',
    name: 'Drinks',
    nameEn: 'Drinks',
    icon: '🍺',
    order: 1,
    isActive: true,
    createdAt: Date.now(),
  },
  {
    _id: 'cat2',
    name: 'Food',
    nameEn: 'Food',
    icon: '🍕',
    order: 2,
    isActive: true,
    createdAt: Date.now(),
  },
  {
    _id: 'cat3',
    name: 'Snacks',
    nameEn: 'Snacks',
    icon: '🍿',
    order: 3,
    isActive: true,
    createdAt: Date.now(),
  },
]

export const demoItems = [
  // Drinks
  {
    _id: 'item1',
    name: 'Corona Beer',
    nameEn: 'Corona Beer',
    description: 'Mexican lager beer',
    price: 25,
    categoryId: 'cat1',
    isAvailable: true,
    stockQuantity: 50,
    minStockLevel: 10,
    tags: ['beer', 'lager'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    _id: 'item2',
    name: 'Heineken',
    nameEn: 'Heineken',
    description: 'Dutch lager beer',
    price: 24,
    categoryId: 'cat1',
    isAvailable: true,
    stockQuantity: 45,
    minStockLevel: 10,
    tags: ['beer', 'lager'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    _id: 'item3',
    name: 'Whiskey',
    nameEn: 'Whiskey',
    description: 'Premium whiskey',
    price: 45,
    categoryId: 'cat1',
    isAvailable: true,
    stockQuantity: 20,
    minStockLevel: 5,
    tags: ['whiskey', 'alcohol'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    _id: 'item4',
    name: 'Vodka',
    nameEn: 'Vodka',
    description: 'Premium vodka',
    price: 40,
    categoryId: 'cat1',
    isAvailable: true,
    stockQuantity: 15,
    minStockLevel: 5,
    tags: ['vodka', 'alcohol'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    _id: 'item5',
    name: 'Coca Cola',
    nameEn: 'Coca Cola',
    description: 'Soft drink',
    price: 12,
    categoryId: 'cat1',
    isAvailable: true,
    stockQuantity: 100,
    minStockLevel: 20,
    tags: ['soft-drink', 'cola'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    _id: 'item6',
    name: 'Orange Juice',
    nameEn: 'Orange Juice',
    description: 'Fresh orange juice',
    price: 15,
    categoryId: 'cat1',
    isAvailable: true,
    stockQuantity: 30,
    minStockLevel: 10,
    tags: ['juice', 'non-alcoholic'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // Food
  {
    _id: 'item7',
    name: 'Burger',
    nameEn: 'Burger',
    description: 'Classic beef burger with fries',
    price: 55,
    categoryId: 'cat2',
    isAvailable: true,
    stockQuantity: 0,
    minStockLevel: 0,
    tags: ['burger', 'main-course'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    _id: 'item8',
    name: 'Pizza Margherita',
    nameEn: 'Pizza Margherita',
    description: 'Classic Italian pizza',
    price: 48,
    categoryId: 'cat2',
    isAvailable: true,
    stockQuantity: 0,
    minStockLevel: 0,
    tags: ['pizza', 'italian'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    _id: 'item9',
    name: 'Caesar Salad',
    nameEn: 'Caesar Salad',
    description: 'Fresh caesar salad',
    price: 38,
    categoryId: 'cat2',
    isAvailable: true,
    stockQuantity: 0,
    minStockLevel: 0,
    tags: ['salad', 'healthy'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    _id: 'item10',
    name: 'Chicken Wings',
    nameEn: 'Chicken Wings',
    description: 'Spicy chicken wings',
    price: 42,
    categoryId: 'cat2',
    isAvailable: true,
    stockQuantity: 0,
    minStockLevel: 0,
    tags: ['chicken', 'appetizer'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // Snacks
  {
    _id: 'item11',
    name: 'French Fries',
    nameEn: 'French Fries',
    description: 'Crispy french fries',
    price: 18,
    categoryId: 'cat3',
    isAvailable: true,
    stockQuantity: 0,
    minStockLevel: 0,
    tags: ['fries', 'side'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    _id: 'item12',
    name: 'Nachos',
    nameEn: 'Nachos',
    description: 'Nachos with cheese and salsa',
    price: 32,
    categoryId: 'cat3',
    isAvailable: true,
    stockQuantity: 0,
    minStockLevel: 0,
    tags: ['nachos', 'appetizer'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    _id: 'item13',
    name: 'Onion Rings',
    nameEn: 'Onion Rings',
    description: 'Crispy onion rings',
    price: 22,
    categoryId: 'cat3',
    isAvailable: true,
    stockQuantity: 0,
    minStockLevel: 0,
    tags: ['onion-rings', 'side'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
]

// Initialize localStorage with demo data if empty
export function initLocalData() {
  const categories = localStorage.getItem('category')
  const items = localStorage.getItem('item')

  if (!categories) {
    localStorage.setItem('category', JSON.stringify(demoCategories))
  }

  if (!items) {
    localStorage.setItem('item', JSON.stringify(demoItems))
  }
}
